import { Router } from 'express';
import authenticateHandler from '../middlewares/auth.middleware';
import { createCompany, getCompaniesById, getCompany } from '../controllers';
import { _admin_role } from '../middlewares/role.middleware';
import { uploadImgCompanies } from '../middlewares/upload.middleware';
const router = Router();
router.use(authenticateHandler);
router.use(_admin_role);
router.get('/', getCompany);
router.get('/information/:id', getCompaniesById);
router.post('/', uploadImgCompanies.fields([{ name: 'img' }]), createCompany);
export default router;
