export { default as UsersServices } from './users.services';
export { default as authServices } from './auth.services';
export { default as ProjectsServices } from './projects.services';
export { default as SubTasksServices } from './subtasks.services';
export { default as ProfileServices } from './profile.services';
export { default as SpecialitiesServices } from './specialities.services';
export { default as PathServices } from './paths.services';
export { default as FilesServices } from './files.services';
export { default as ReportsServices } from './reports.services';
export { default as FeedBackServices } from './feedbacks.services';
export { default as DuplicatesServices } from './duplicates.services';
export { default as StageServices } from './stages.services';
export { default as SectorServices } from './sector.services';
export { default as TypeSpecialitiesServices } from './typeSpecialities.services';
export { default as LevelsServices } from './levels.services';
export { default as ListServices } from './list.services';
export { default as PayMailServices } from './payMail.services';
export { default as LicenseServices } from './licenses.services';
export { default as CompaniesServices } from './companies.services';
export { default as SpecialistServices } from './specialist.services';
export { default as AreaSpecialtyServices } from './areaSpecialty.services';
export { default as TrainingSpecialtyServices } from './trainingSpecialty.services';
export { default as AreaSpecialtyListServices } from './areaSpecialtyList.services';
export { default as TrainingSpecialtyListServices } from './trainingSpecialtyList.services';
export { default as WorkStationServices } from './workStation.services';
export { default as EquipmentServices } from './equipment.services';
export { default as ContractServices } from './contract.services';
export { default as ConsortiumServices } from './consortium.services';
export { default as GroupServices } from './groups.services';
export { default as AttendanceGroupService } from './attendanceGroup.services';
export { default as DutyServices } from './duty.services';
export { default as DutyMembersServices } from './dutyMembers.services';
export { default as BasicLevelServices } from './basiclevels.services';
export { default as BasicTasksServices } from './basictask.services';
export { default as OfficeServices } from './office.services';
export { default as ListSpecialties } from './listSpecialties.services';
export { default as DowloadServices } from './download.services';
export { default as AsitecServices } from './asitec.services';

export const rootPath = './uploads';
export const indexPath = './index';
export const _dirPath = `${rootPath}/projects`;
export const _materialPath = `${rootPath}/models`;
export const _reviewPath = `${rootPath}/reviews`;
export const _editablePath = `${rootPath}/editables`;
export const _contractPath = `${indexPath}/contracts`;
