import globalErrorHandler from './error.middleware';
import { verifyFiles } from './files.middlewares';
import { verifyStatusUser } from './user.middleware';
import docs from './docs.middleware';
export { verifyFiles };
export { globalErrorHandler, verifyStatusUser };
export { docs };
export { uploads };
import { default as uploads } from './upload.middleware';
export { default as authenticateHandler } from './auth.middleware';
export { default as role } from './role.middleware';
